// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'debug'
	| 'en'
	| 'fr'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	profile: {
		navigation: {
			/**
			 * P​r​o​f​i​l​e
			 */
			profile: string
			/**
			 * S​e​t​t​i​n​g​s
			 */
			settings: string
		}
		display: {
			/**
			 * N​a​m​e
			 */
			name: string
			/**
			 * A​v​a​t​a​r
			 */
			avatar: string
			/**
			 * E​m​a​i​l
			 */
			email: string
		}
		action: {
			/**
			 * L​o​g​o​u​t
			 */
			logout: string
			/**
			 * D​e​l​e​t​e​ ​A​c​c​o​u​n​t
			 */
			deleteAccount: string
		}
	}
	project: {
		navigation: {
			/**
			 * O​v​e​r​v​i​e​w
			 */
			overview: string
			/**
			 * I​n​f​o​r​m​a​t​i​o​n​s
			 */
			info: string
			/**
			 * C​o​l​o​r​s
			 */
			colors: string
			/**
			 * T​h​e​m​e​s
			 */
			themes: string
		}
	}
}

export type TranslationFunctions = {
	profile: {
		navigation: {
			/**
			 * Profile
			 */
			profile: () => LocalizedString
			/**
			 * Settings
			 */
			settings: () => LocalizedString
		}
		display: {
			/**
			 * Name
			 */
			name: () => LocalizedString
			/**
			 * Avatar
			 */
			avatar: () => LocalizedString
			/**
			 * Email
			 */
			email: () => LocalizedString
		}
		action: {
			/**
			 * Logout
			 */
			logout: () => LocalizedString
			/**
			 * Delete Account
			 */
			deleteAccount: () => LocalizedString
		}
	}
	project: {
		navigation: {
			/**
			 * Overview
			 */
			overview: () => LocalizedString
			/**
			 * Informations
			 */
			info: () => LocalizedString
			/**
			 * Colors
			 */
			colors: () => LocalizedString
			/**
			 * Themes
			 */
			themes: () => LocalizedString
		}
	}
}

export type Formatters = {}
